// Airport index. The dataset (~3,300 airports with scheduled service, generated by
// scripts/build-airports.mjs) is code-split and loaded on first use.

let index = null;
let loading = null;

const fold = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();
const regionNames = typeof Intl.DisplayNames === 'function' ? new Intl.DisplayNames(['en'], { type: 'region' }) : null;

function countryName(code) {
  try { return regionNames?.of(code) ?? code; } catch { return code; }
}

export function loadAirports() {
  loading ??= import('../data/airports.json').then(({ default: rows }) => {
    index = rows.map(([iata, name, city, country, lat, lon, tz]) => ({
      iata, name, city, country, countryName: countryName(country), lat, lon, tz,
      _city: fold(city), _name: fold(name), _country: fold(countryName(country)),
    }));
    return index;
  });
  return loading;
}

export function findAirport(iata) {
  if (!index || !iata) return null;
  const code = iata.toUpperCase();
  return index.find((a) => a.iata === code) ?? null;
}

export function searchAirports(query, limit = 8) {
  if (!index) return [];
  const q = fold(query.trim());
  if (!q) return [];
  const scored = [];
  for (const a of index) {
    const code = a.iata.toLowerCase();
    let score = 0;
    if (code === q) score = 100;
    else if (a._city === q) score = 80;
    else if (code.startsWith(q)) score = 70;
    else if (a._city.startsWith(q)) score = 60;
    else if (a._name.startsWith(q)) score = 50;
    else if (a._city.includes(q)) score = 40;
    else if (a._name.includes(q)) score = 30;
    else if (q.length > 3 && a._country.startsWith(q)) score = 20;
    if (score) scored.push([score, a]);
  }
  scored.sort((x, y) => y[0] - x[0] || x[1].iata.localeCompare(y[1].iata));
  return scored.slice(0, limit).map(([, a]) => a);
}
